# Generated by Django 3.2.5 on 2022-12-23 09:37

import base_services.models.custom_type
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStoreModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', base_services.models.custom_type.TinyIntegerField(db_index=True, default=1)),
            ],
            options={
                'db_table': 'email_store',
            },
        ),
    ]
