# Generated by Django 3.2.5 on 2023-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authrefreshtoken',
            name='access_token',
        ),
        migrations.AlterField(
            model_name='authrefreshtoken',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
