# Generated by Django 3.2.5 on 2023-02-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230208_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_tokens',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
