# Generated by Django 3.2.5 on 2023-02-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_used_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_tokens',
            field=models.IntegerField(default=0, max_length=10000, null=True),
        ),
    ]
